### ISSUE TITLE
DNSSEC

### ISSUE THREAD

**Issue by Madis0** [jannispinter/indicatetls#12]
I don't know much about it, but I've heard it does help verify the authenticity of the site on DNS level. So it would be nice if this was shown.

Inspired by https://addons.mozilla.org/en-US/firefox/addon/dnssec/ and https://addons.mozilla.org/en-US/firefox/addon/httpspluschecker/

**Comment by jannispinter** [comment]
Thanks! This is quite difficult and requires you (as far as i know) to do DNS lookups from within the extension. That again sends the browsing history to a third party (the DNS provider, which may be a different DNS provider the browser uses) which is not what many people want.

Because of this, I think it is beyond the scope of this extension. Also there are already some dedicated extensions for DNSSEC (as you have mentioned) that seem to work quite well. For users interested in DNSSEC I would recommend using those.
